name: ci

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  matrix:
    strategy:
      matrix:
        go-version: [1.15.x, 1.14.x, 1.13.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - run: go get -v -t -d ./...
    - run: go test -v ./...
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Coverage on latest 1.x Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.*
    - uses: actions/checkout@v2
    - run: go get -v -t -d ./...
    - run: go test -v -coverprofile=coverage.out -covermode=count ./...
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
        fail_ci_if_error: true
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34
          only-new-issues: true
