name: go-matrix

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  matrix:
    strategy:
      matrix:
        go-version: [1.15.x, 1.14.x, 1.13.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - run: go get -v -t -d ./...
    - run: go test -v ./...
