name: go-proxy-warming

on:
  release:
    types:
      - created
    tags: [ v* ]
  push:
    tags: [ v* ]

jobs:
  go-proxy-warming:
    runs-on: ubuntu-latest
    steps:
    - uses: andrewslotin/go-proxy-pull-action@master
